Movie.create(:title => "Pulp Fiction", :description => "The lives of two mob hitmen, a boxer, a gangster & his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", :director => "Quentin Tarantino", :year => 1994)
Movie.create(:title => "Harakiri", :description => "An elder ronin samurai arrives at a feudal lord's home and requests an honorable place to commit suicide. But when the ronin inquires about a younger samurai who arrived before him things take an unexpected turn.", :director => "Masaki Kobayashi", :year => 1962)
Movie.create(:title => "The Man from Earth", :description => "An impromptu goodbye party for Professor John Oldman becomes a mysterious interrogation after the retiring scholar reveals to his colleagues he has a longer and stranger past than they can imagine..", :director => "Richard Schenkman", :year => 2007)
Movie.create(:title => "Vertigo", :description => "A former police detective juggles wrestling with his personal demons and becoming obsessed with a hauntingly beautiful woman.", :director => "Alfred Hitchcock", :year => 1958)
Movie.create(:title => "The Departed", :description => "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", :director => "Martin Scorsese", :year => 2006)
Movie.create(:title => "12 Angry Men", :description => "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.", :director => "Sidney Lumet", :year => 1957)
Movie.create(:title => "Breakfast at Tiffany's", :description => "A young New York socialite becomes interested in a young man who has moved into her apartment building, but her past threatens to get in the way.", :director => "Blake Edwards", :year => 1961)
Movie.create(:title => "About Time", :description => "At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you might think.", :director => "Richard Curtis", :year => 2013)
Movie.create(:title => "Her", :description => "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.", :director => "Spike Jonze", :year => 2013)
Movie.create(:title => "Black Swan", :description => "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's 'Swan Lake'.", :director => "Darren Aronofsky", :year => 2010)
Movie.create(:title => "Anomalisa", :description => "A man crippled by the mundanity of his life experiences something out of the ordinary.", :director => "Duke Johnson, Charlie Kaufman", :year => 2015)
Movie.create(:title => "Fight Club", :description => "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.", :director => "David Fincher", :year => 1999)
Movie.create(:title => "Misery", :description => "After a famous author is rescued from a car crash by a fan of his novels, he comes to realize that the care he is receiving is only the beginning of a nightmare of captivity and abuse.", :director => "Rob Reiner", :year => 1990)
Movie.create(:title => "Amélie", :description => "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.", :director => "Jean-Pierre Jeunet", :year => 2001)
Movie.create(:title => "Eternal Sunshine of the Spotless Mind", :description => "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.", :director => "Michel Gondry", :year => 2004)
Movie.create(:title => "A Beautiful Mind", :description => "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.", :director => "Ron Howard", :year => 2001)
Movie.create(:title => "The Lobster", :description => "In a dystopian near future, single people, according to the laws of The City, are taken to The Hotel, where they are obliged to find a romantic partner in forty-five days or are transformed into beasts and sent off into The Woods.", :director => " Yorgos Lanthimos", :year => 2015)
Movie.create(:title => "Ran", :description => "In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, he vastly underestimates how the new-found power will corrupt them and cause them to turn on each other...and him.", :director => "Akira Kurosawa", :year => 1985)
Movie.create(:title => "The Grand Budapest Hotel", :description => "The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.", :director => "Wes Anderson", :year => 2014)
Movie.create(:title => "Juno", :description => "Faced with an unplanned pregnancy, an offbeat young woman makes an unusual decision regarding her unborn child.", :director => "Jason Reitman", :year => 2007)
Movie.create(:title => "The Matrix", :description => "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", :director => "Lana and Lilly Wachowski (as The Wachowski Brothers)", :year => 1999)
Movie.create(:title => "Wild Tales", :description => "Six short stories that explore the extremities of human behavior involving people in distress.", :director => "Damián Szifron", :year => 2014)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)